POST https://qt7t7sp8-3000.euw.devtunnels.ms/api/bookings
Content-Type: application/json

{
    "bookings":
    [
        {
            "timeSlot": "10-11",
            "machineNumber": 1,
            "personName": "Ola Nordmann",
            "dateString": "2023-12-29"
        },
                {
            "timeSlot": "10-11",
            "machineNumber": 3,
            "personName": "Ola Nordmann",
            "dateString": "2023-12-29"
        },
                {
            "timeSlot": "10-11",
            "machineNumber": 2,
            "personName": "Ola Nordmann",
            "dateString": "2023-12-29"
        }
    ]
}